### ISSUE TITLE
6.3 , 6.4 

### ISSUE THREAD

**Issue by roozbehk** [Multimedia-Business-Services/jira-shibboleth-connector#1]
Are you planning to work on making your plugin compatible with 6.3, 6.4?

**Comment by valeriominetti** [comment]
this seems to be working with my 6.4.12 just updating pom.xml file with the new jira and amps version numbers

**Comment by r0mdau** [comment]
Hello,
It's working with Jira 6.4. And now we use 7.2.7 with this plugin.
@valeriominetti :+1:
